name: sunnypilot prebuilt action
env:
  BUILD_DIR: /data/openpilot
  OUTPUT_DIR: ${{ github.workspace }}/output
  CI_DIR: ${{ github.workspace }}/release/ci
  SCONS_CACHE_DIR: ${{ github.workspace }}/release/ci/scons_cache
  PUBLIC_REPO_URL: https://github.com/sunnypilot/sunnypilot
  STAGING_C3_SOURCE_BRANCH: ${{ vars.STAGING_C3_SOURCE_BRANCH || 'master-new' }}
  DEV_C3_SOURCE_BRANCH: ${{ vars.DEV_C3_SOURCE_BRANCH || 'master-dev-c3-new' }}
  STAGING_TARGET_BRANCH: ${{ vars.STAGING_TARGET_BRANCH || 'staging-c3-new' }}
  DEV_TARGET_BRANCH: ${{ vars.DEV_TARGET_BRANCH || 'dev-c3-new' }}
  RELEASE_TARGET_BRANCH: ${{ vars.RELEASE_TARGET_BRANCH || 'release-c3-new' }}
  SOURCE_BRANCH: ${{ github.head_ref || github.ref_name }}
'on':
  push:
    branches:
    - master
    - master-new
    - master-dev-c3-new
    tags:
    - '*'
  pull_request_target:
    types:
    - labeled
  workflow_dispatch:
    inputs:
      wait_for_tests:
        description: Wait for selfdrive_tests to finish
        required: false
        type: boolean
        default: false
jobs:
  validate_tests:
    runs-on: ubuntu-24.04
    if: ((github.event_name == 'workflow_dispatch' && inputs.wait_for_tests) || contains(github.event_name,
      'pull_request') && (github.event.action == 'labeled' && github.event.label.name
      == 'prebuilt'))
    steps:
    - uses: actions/checkout@v4
    - name: Wait for Tests
      uses: ./.github/workflows/wait-for-action
      with:
        workflow: selfdrive_tests.yaml
        github-token: ${{ secrets.GITHUB_TOKEN }}
  build:
    needs:
    - validate_tests
    concurrency:
      group: build-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: false
    runs-on: ubuntu-latest
    outputs:
      new_branch: ${{ steps.set-env.outputs.new_branch }}
      version: ${{ steps.set-env.outputs.version }}
      extra_version_identifier: ${{ steps.set-env.outputs.extra_version_identifier
        }}
      commit_sha: ${{ steps.set-env.outputs.commit_sha }}
    if: ${{ (always() && !failure() && !cancelled()) && (!contains(github.event_name,
      'pull_request') || (github.event.action == 'labeled' && github.event.label.name
      == 'prebuilt')) }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        ref: ${{ env.SOURCE_BRANCH }}
        repository: ${{ github.event.pull_request.head.repo.fork && github.event.pull_request.head.repo.full_name
          || github.repository }}
    - run: git lfs pull
    - name: Cache SCons
      uses: actions/cache@v4
      with:
        path: ${{env.SCONS_CACHE_DIR}}
        key: scons-${{ runner.os }}-${{ runner.arch }}-${{ env.SOURCE_BRANCH }}-${{
          github.sha }}
        restore-keys: 'scons-${{ runner.os }}-${{ runner.arch }}-${{ env.SOURCE_BRANCH
          }}

          scons-${{ runner.os }}-${{ runner.arch }}-${{ env.STAGING_C3_SOURCE_BRANCH
          }}

          scons-${{ runner.os }}-${{ runner.arch }}

          '
    - name: Set Feature Branch Prebuilt Configuration
      id: set_feature_configuration
      if: ( !(env.SOURCE_BRANCH == env.DEV_C3_SOURCE_BRANCH) && !(env.SOURCE_BRANCH
        == env.STAGING_C3_SOURCE_BRANCH) && !(startsWith(github.ref, 'refs/tags/'))
        )
      run: 'echo "NEW_BRANCH=${{ env.SOURCE_BRANCH }}${{ github.event.pull_request.head.repo.fork
        && ''-fork'' || '''' }}-prebuilt" >> $GITHUB_ENV

        echo "VERSION=$(date ''+%Y.%m.%d'')-${{ github.run_number }}" >> $GITHUB_ENV

        '
    - name: Set dev-c3-new prebuilt Configuration
      id: set_dev_configuration
      if: ( steps.set_feature_configuration.outcome == 'skipped' && env.SOURCE_BRANCH
        == env.DEV_C3_SOURCE_BRANCH )
      run: 'echo "NEW_BRANCH=${{ env.DEV_TARGET_BRANCH }}" >> $GITHUB_ENV

        echo "VERSION=$(date ''+%Y.%m.%d'')-${{ github.run_number }}" >> $GITHUB_ENV

        echo "EXTRA_VERSION_IDENTIFIER=${{ github.run_number }}" >> $GITHUB_ENV

        '
    - name: Set staging-c3-new prebuilt Configuration
      id: set_staging_configuration
      if: ( steps.set_feature_configuration.outcome == 'skipped' && !contains(github.event_name,
        'pull_request') && steps.set_dev_configuration.outcome == 'skipped' && (env.SOURCE_BRANCH
        == env.STAGING_C3_SOURCE_BRANCH) )
      run: 'echo "NEW_BRANCH=${{ env.STAGING_TARGET_BRANCH }}" >> $GITHUB_ENV

        echo "EXTRA_VERSION_IDENTIFIER=staging" >> $GITHUB_ENV

        echo "VERSION=$(cat common/version.h | grep COMMA_VERSION | sed -e ''s/[^0-9|.]//g'')-staging"
        >> $GITHUB_ENV

        '
    - name: Set release-c3-new prebuilt Configuration
      id: set_tag_configuration
      if: ( steps.set_feature_configuration.outcome == 'skipped' && !contains(github.event_name,
        'pull_request') && steps.set_staging_configuration.outcome == 'skipped' &&
        startsWith(github.ref, 'refs/tags/') )
      run: 'echo "NEW_BRANCH=${{ env.RELEASE_TARGET_BRANCH }}" >> $GITHUB_ENV

        echo "EXTRA_VERSION_IDENTIFIER=release" >> $GITHUB_ENV

        echo "VERSION=$(cat common/version.h | grep COMMA_VERSION | sed -e ''s/[^0-9|.]//g'')-release"
        >> $GITHUB_ENV

        '
    - name: Set environment variables
      id: set-env
      run: "# Write to GITHUB_OUTPUT from environment variables\necho \"new_branch=$NEW_BRANCH\"\
        \ >> $GITHUB_OUTPUT\n[[ ! -z \"$EXTRA_VERSION_IDENTIFIER\" ]] && echo \"extra_version_identifier=$EXTRA_VERSION_IDENTIFIER\"\
        \ >> $GITHUB_OUTPUT\n[[ ! -z \"$VERSION\" ]] && echo \"version=$VERSION\"\
        \ >> $GITHUB_OUTPUT\necho \"commit_sha=${{ github.sha }}\" >> $GITHUB_OUTPUT\n\
        \n# Set up common environment\nsource /etc/profile;\nexport UV_PROJECT_ENVIRONMENT=${HOME}/venv\n\
        export VIRTUAL_ENV=$UV_PROJECT_ENVIRONMENT\nprintenv >> $GITHUB_ENV\nif [[\
        \ \"${{ runner.debug }}\" == \"1\" ]]; then\n  cat $GITHUB_OUTPUT\nfi\n"
    - name: Setup build environment
      run: "mkdir -p \"${BUILD_DIR}/\"\nsudo find $BUILD_DIR/ -mindepth 1 -delete\n\
        echo \"Starting build stage...\"\necho \"BUILD_DIR: ${BUILD_DIR}\"\necho \"\
        CI_DIR: ${CI_DIR}\"\necho \"VERSION: ${{ steps.set-env.outputs.version }}\"\
        \necho \"UV_PROJECT_ENVIRONMENT: ${UV_PROJECT_ENVIRONMENT}\"\necho \"VIRTUAL_ENV:\
        \ ${VIRTUAL_ENV}\"\necho \"-------\"\nif [[ \"${{ runner.debug }}\" == \"\
        1\" ]]; then\n  printenv\nfi\nPYTHONPATH=$PYTHONPATH:${{ github.workspace\
        \ }}/ ${{ github.workspace }}/scripts/manage-powersave.py --disable\n"
    - name: Build Main Project
      run: "export PYTHONPATH=\"$BUILD_DIR\"\n./release/release_files.py | sort |\
        \ uniq | rsync -rRl${RUNNER_DEBUG:+v} --files-from=- . $BUILD_DIR/\ncd $BUILD_DIR\n\
        sed -i '/from .board.jungle import PandaJungle, PandaJungleDFU/s/^/#/' panda/__init__.py\n\
        scons -j$(nproc) cache_dir=${{env.SCONS_CACHE_DIR}} --minimal\ntouch ${BUILD_DIR}/prebuilt\n\
        if [[ \"${{ runner.debug }}\" == \"1\" ]]; then\n  ls -la ${BUILD_DIR}\nfi\n"
    - name: Prepare Output
      run: "sudo rm -rf ${OUTPUT_DIR}\nmkdir -p ${OUTPUT_DIR}\nrsync -am${RUNNER_DEBUG:+v}\
        \ \\\n  --include='**/panda/board/' \\\n  --include='**/panda/board/obj' \\\
        \n  --include='**/panda/board/obj/panda.bin.signed' \\\n  --include='**/panda/board/obj/panda_h7.bin.signed'\
        \ \\\n  --include='**/panda/board/obj/bootstub.panda.bin' \\\n  --include='**/panda/board/obj/bootstub.panda_h7.bin'\
        \ \\\n  --exclude='.sconsign.dblite' \\\n  --exclude='*.a' \\\n  --exclude='*.o'\
        \ \\\n  --exclude='*.os' \\\n  --exclude='*.pyc' \\\n  --exclude='moc_*' \\\
        \n  --exclude='*.cc' \\\n  --exclude='Jenkinsfile' \\\n  --exclude='supercombo.onnx'\
        \ \\\n  --exclude='**/panda/board/*' \\\n  --exclude='**/panda/board/obj/**'\
        \ \\\n  --exclude='**/panda/certs/' \\\n  --exclude='**/panda/crypto/' \\\n\
        \  --exclude='**/release/' \\\n  --exclude='**/.github/' \\\n  --exclude='**/selfdrive/ui/replay/'\
        \ \\\n  --exclude='**/__pycache__/' \\\n  --exclude='**/selfdrive/ui/*.h'\
        \ \\\n  --exclude='**/selfdrive/ui/**/*.h' \\\n  --exclude='**/selfdrive/ui/qt/offroad/sunnypilot/'\
        \ \\\n  --exclude='${{env.SCONS_CACHE_DIR}}' \\\n  --exclude='**/.git/' \\\
        \n  --exclude='**/SConstruct' \\\n  --exclude='**/SConscript' \\\n  --exclude='**/.venv/'\
        \ \\\n  --delete-excluded \\\n  --chown=comma:comma \\\n  ${BUILD_DIR}/ ${OUTPUT_DIR}/\n"
    - name: Tar.gz files
      run: 'tar czf prebuilt.tar.gz -C ${{ env.OUTPUT_DIR }} .

        ls -la prebuilt.tar.gz

        '
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: prebuilt
        path: prebuilt.tar.gz
    - name: Re-enable powersave
      if: always()
      run: 'PYTHONPATH=$PYTHONPATH:${{ github.workspace }}/ ${{ github.workspace }}/scripts/manage-powersave.py
        --enable

        '
  publish:
    concurrency:
      group: publish-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
    if: ${{ (always() && !failure() && !cancelled()) && (!contains(github.event_name,
      'pull_request') || (github.event.action == 'labeled' && github.event.label.name
      == 'prebuilt')) }}
    needs:
    - build
    runs-on: ubuntu-24.04
    environment: ${{ (contains(fromJSON(vars.AUTO_DEPLOY_PREBUILT_BRANCHES), github.head_ref
      || github.ref_name) || contains(github.event.pull_request.labels.*.name, 'prebuilt'))
      && 'auto-deploy' || 'feature-branch' }}
    steps:
    - uses: actions/checkout@v4
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: prebuilt
    - name: Untar prebuilt
      run: 'mkdir -p ${{ env.OUTPUT_DIR }}

        tar xzf prebuilt.tar.gz -C ${{ env.OUTPUT_DIR }}

        '
    - name: Configure Git
      run: 'git config --global user.email "github-actions[bot]@users.noreply.github.com"

        git config --global user.name "github-actions[bot]"

        '
    - name: Publish to Public Repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: "echo '${{ toJSON(needs.build.outputs) }}'\nls -la ${{ env.OUTPUT_DIR }}\n\
        \n${{ env.CI_DIR }}/publish.sh \\\n  \"${{ github.workspace }}\" \\\n  \"\
        ${{ env.OUTPUT_DIR }}\" \\\n  \"${{ needs.build.outputs.new_branch }}\" \\\
        \n  \"${{ needs.build.outputs.version }}\" \\\n  \"https://x-access-token:${{github.token}}@github.com/sunnypilot/sunnypilot.git\"\
        \ \\\n  \"-${{ needs.build.outputs.extra_version_identifier }}\"\n\necho \"\
        \"\necho \"----   \u2139\uFE0F To update the list of branches that auto deploy\
        \ prebuilts  -----\"\necho \"\"\necho \"1. Go to: ${{ github.server_url }}/${{\
        \ github.repository }}/settings/variables/actions/AUTO_DEPLOY_PREBUILT_BRANCHES\"\
        \necho \"2. Current value: ${{ vars.AUTO_DEPLOY_PREBUILT_BRANCHES }}\"\necho\
        \ \"3. Update as needed (JSON array with no spaces)\"\n"
  notify:
    needs:
    - build
    - publish
    runs-on: ubuntu-24.04
    if: ${{ (always() && !failure() && !cancelled()) && (!contains(github.event_name,
      'pull_request') || (github.event.action == 'labeled' && github.event.label.name
      == 'prebuilt')) }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Alpine Linux environment
      uses: jirutka/setup-alpine@v1.2.0
      with:
        packages: jq gettext curl
    - name: Send Discord Notification
      env:
        DISCORD_WEBHOOK: ${{ contains(fromJSON(vars.DEV_FEEDBACK_NOTIFICATION_BRANCHES),
          env.SOURCE_BRANCH) && secrets.DISCORD_DEV_FEEDBACK_CHANNEL_WEBHOOK || secrets.DISCORD_DEV_PRIVATE_CHANNEL_WEBHOOK
          }}
      run: "TEMPLATE='${{ vars.DISCORD_GENERAL_UPDATE_NOTICE }}'\nexport EXTRA_VERSION_IDENTIFIER=\"\
        ${{ needs.build.outputs.extra_version_identifier }}\"\nexport VERSION=\"${{\
        \ needs.build.outputs.version }}\"\nexport branch_name=${{ env.SOURCE_BRANCH\
        \ }}\nexport new_branch=${{ needs.build.outputs.new_branch }}\nexport extra_version_identifier=${{\
        \ needs.build.outputs.extra_version_identifier || github.run_number}}\necho\
        \ ${TEMPLATE} | envsubst | jq -c '.' | tee payload.json\ncurl -X POST -H \"\
        Content-Type: application/json\" -d @payload.json $DISCORD_WEBHOOK\n\necho\
        \ \"\"\necho \"----   \u2139\uFE0F To update the list of branches that notify\
        \ to dev-feedback  -----\"\necho \"\"\necho \"1. Go to: ${{ github.server_url\
        \ }}/${{ github.repository }}/settings/variables/actions/DEV_FEEDBACK_NOTIFICATION_BRANCHES\"\
        \necho \"2. Current value: ${{ vars.DEV_FEEDBACK_NOTIFICATION_BRANCHES }}\"\
        \necho \"3. Update as needed (JSON array with no spaces)\"\n"
      shell: alpine.sh {0}
  manage-pr-labels:
    name: Remove prebuilt label
    runs-on: ubuntu-latest
    if: (always() && contains(github.event_name, 'pull_request') && (github.event.action
      == 'labeled' && github.event.label.name == 'prebuilt'))
    env:
      LABEL: prebuilt
    steps:
    - name: Remove trust-fork-pr label if present
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: "const prNumber = context.payload.pull_request.number;\n\nawait github.rest.issues.removeLabel({\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n  issue_number:\
          \ prNumber,\n  name: process.env.LABEL\n});\n\nconsole.log(`Removed '${process.env.LABEL}'\
          \ label from PR #${prNumber}`);\n"
